version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  
  base: &base
    build: .

  web:
    << : *base
    container_name: web
    command: >
      sh -c " python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py test &&
        python migration.py &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db